require 'pry'
require 'nokogiri'
require 'open-uri'

require_relative '../lib/classifieds/version.rb'
require_relative '../lib/classifieds/cli.rb'
require_relative '../lib/classifieds/item.rb'
require_relative '../lib/classifieds/listing.rb'
require_relative '../lib/classifieds/seller.rb'
require_relative '../lib/classifieds/vehicle.rb'
require_relative '../lib/classifieds/string_reverse.rb'
require_relative '../lib/classifieds/boat.rb'
require_relative '../lib/classifieds/auto_scraper.rb'
require_relative '../lib/classifieds/boat_scraper.rb'
